version: '3.9'

services:
  db:
    image: postgres:15
    container_name: shining_db
    restart: always
    environment:
      POSTGRES_DB: shining_smiles
      POSTGRES_USER: ss_admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: shining_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://ss_admin:root@db:5432/shining_smiles
      - DEBUG=1

volumes:
  postgres_data:
